# Generated by Django 3.0.8 on 2021-06-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('Email', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
    ]
