# Generated by Django 3.0.8 on 2021-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactcarrers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contactprojects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contactservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contactone',
        ),
    ]
