# Generated by Django 3.0.8 on 2021-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvelapp', '0002_auto_20210616_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
